name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Increment patch version
      run: |
        #get latest tag
        LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.0")
        VERSION_WITHOUT_V=${LATEST_TAG#v}
        
        #increment patch
        IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION_WITHOUT_V"
        NEW_VERSION="1.0.$((PATCH + 1))"
        
        #update pom.xml
        mvn versions:set -DnewVersion=$NEW_VERSION -DgenerateBackupPoms=false
        
        echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV
    
    - name: Build with Maven
      run: mvn clean package
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/simple-java-app:${{ env.VERSION }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/simple-java-app:${{ env.VERSION }}
    
    - name: Create version tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag -a v${{ env.VERSION }} -m "Version ${{ env.VERSION }}"
        git push origin v${{ env.VERSION }}
